//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Inputs/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""4f21c1d2-b223-45be-82ce-a4c4f7703c46"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""faf1d81b-961e-4b51-a4ba-bbf73b848294"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pointer Position"",
                    ""type"": ""Value"",
                    ""id"": ""08b48acd-f4fd-4d30-8887-e7d9cef4d443"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AttackMainHand"",
                    ""type"": ""Button"",
                    ""id"": ""b6e4faac-d540-4546-b3ec-247340f8f0dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackOffHand"",
                    ""type"": ""Button"",
                    ""id"": ""f30d7e66-c6ea-48c7-997e-4fab32af75c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Weapon"",
                    ""type"": ""Value"",
                    ""id"": ""998c6550-a423-4173-8e81-4f3b01ffe040"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Overview Map Full View"",
                    ""type"": ""Button"",
                    ""id"": ""8ef4a6d8-de97-406e-8e85-cc75142a6d06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Next Level"",
                    ""type"": ""Button"",
                    ""id"": ""3b0e4693-45cd-4916-a40b-cd72c5b3fd82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""f6a57153-f43f-49a1-a783-3142b3dcd37d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special Move1"",
                    ""type"": ""Button"",
                    ""id"": ""18d82115-ffab-441e-8d09-3ba1ec79990b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special Move2"",
                    ""type"": ""Button"",
                    ""id"": ""51383c56-5677-4948-b9f9-6c6a8c09340d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special Move3"",
                    ""type"": ""Button"",
                    ""id"": ""46ae1878-7aca-4762-8ed3-8e1dd8568c34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Book View"",
                    ""type"": ""Button"",
                    ""id"": ""7dc35769-e66a-4a05-b64f-65457e84e1cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Active Item"",
                    ""type"": ""Button"",
                    ""id"": ""e519b454-f121-4a2a-83d1-e7e4bcf37a0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop Active Item"",
                    ""type"": ""Button"",
                    ""id"": ""57a24197-87d1-451b-b001-6978b6035f29"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""b30105a8-6f93-4de1-8386-2d72d9be7ff5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OK"",
                    ""type"": ""Button"",
                    ""id"": ""31262818-23d1-4859-bfcc-3e1d071d4a34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""ba81aa0c-1493-458c-a89f-3607f09eba71"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""f4e4659e-a832-4627-9a7e-505e3cf1a47f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bd7a88cf-dad0-449e-a596-e9b1a4f53e19"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""30d98811-04b5-4bc2-bc63-5007e9dec8ea"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7075de21-c567-423e-93ab-034b411be81f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c6e0dd7a-2aca-4429-b0a6-2d88810ac39f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""aa6189b2-b85e-4b77-ba73-1d9537e4e5e4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""902b3e87-4344-4d8f-8920-dee756966378"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fde89b0a-3635-48a2-8201-451d4287e906"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dc77f91c-f1d1-4e47-8a9e-fa592bbaa03a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""518d28dd-423f-43a9-b134-650326050201"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""86fb0878-bfac-4897-ac76-07495ed1ddba"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pointer Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04ade5ee-43f2-441b-bcd1-0069021e4ef4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackMainHand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d47e589-c7ce-4ddb-980d-792c58f9d643"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackOffHand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""baae79a6-3d76-42aa-a4d6-f92cd70041e1"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""217bcf8d-be23-4e25-887d-82f369552288"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Overview Map Full View"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""216c61bc-6459-40d3-ad95-18ab2ddb2eb2"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next Level"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""244ce1a2-fb9e-4bab-b713-3dd66aa7e4c3"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9ef3500-fe44-49cb-82f5-869a154baee1"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9005a554-be1b-4f34-912e-4a59d030f8d8"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Book View"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1731449d-00a5-43c3-a4f4-711df9d74d92"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Active Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d8f7d31-fb01-41c7-b9f8-1d8c8e814874"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop Active Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""692cb854-aea5-4aed-8278-05cb71eba076"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53fcfa54-f0e4-48fa-804e-4e62c8b2ad69"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""004bc29e-8e97-4784-8ea3-b0d742c819ec"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Move3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59830bbf-568c-4d8e-ae29-5c33d79af385"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a16c5117-9d98-43dd-a26c-0ed587577081"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Movement = m_PlayerInput.FindAction("Movement", throwIfNotFound: true);
        m_PlayerInput_PointerPosition = m_PlayerInput.FindAction("Pointer Position", throwIfNotFound: true);
        m_PlayerInput_AttackMainHand = m_PlayerInput.FindAction("AttackMainHand", throwIfNotFound: true);
        m_PlayerInput_AttackOffHand = m_PlayerInput.FindAction("AttackOffHand", throwIfNotFound: true);
        m_PlayerInput_SwitchWeapon = m_PlayerInput.FindAction("Switch Weapon", throwIfNotFound: true);
        m_PlayerInput_OverviewMapFullView = m_PlayerInput.FindAction("Overview Map Full View", throwIfNotFound: true);
        m_PlayerInput_NextLevel = m_PlayerInput.FindAction("Next Level", throwIfNotFound: true);
        m_PlayerInput_Interaction = m_PlayerInput.FindAction("Interaction", throwIfNotFound: true);
        m_PlayerInput_SpecialMove1 = m_PlayerInput.FindAction("Special Move1", throwIfNotFound: true);
        m_PlayerInput_SpecialMove2 = m_PlayerInput.FindAction("Special Move2", throwIfNotFound: true);
        m_PlayerInput_SpecialMove3 = m_PlayerInput.FindAction("Special Move3", throwIfNotFound: true);
        m_PlayerInput_BookView = m_PlayerInput.FindAction("Book View", throwIfNotFound: true);
        m_PlayerInput_ActiveItem = m_PlayerInput.FindAction("Active Item", throwIfNotFound: true);
        m_PlayerInput_DropActiveItem = m_PlayerInput.FindAction("Drop Active Item", throwIfNotFound: true);
        m_PlayerInput_Pause = m_PlayerInput.FindAction("Pause", throwIfNotFound: true);
        m_PlayerInput_OK = m_PlayerInput.FindAction("OK", throwIfNotFound: true);
        m_PlayerInput_Jump = m_PlayerInput.FindAction("Jump", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private List<IPlayerInputActions> m_PlayerInputActionsCallbackInterfaces = new List<IPlayerInputActions>();
    private readonly InputAction m_PlayerInput_Movement;
    private readonly InputAction m_PlayerInput_PointerPosition;
    private readonly InputAction m_PlayerInput_AttackMainHand;
    private readonly InputAction m_PlayerInput_AttackOffHand;
    private readonly InputAction m_PlayerInput_SwitchWeapon;
    private readonly InputAction m_PlayerInput_OverviewMapFullView;
    private readonly InputAction m_PlayerInput_NextLevel;
    private readonly InputAction m_PlayerInput_Interaction;
    private readonly InputAction m_PlayerInput_SpecialMove1;
    private readonly InputAction m_PlayerInput_SpecialMove2;
    private readonly InputAction m_PlayerInput_SpecialMove3;
    private readonly InputAction m_PlayerInput_BookView;
    private readonly InputAction m_PlayerInput_ActiveItem;
    private readonly InputAction m_PlayerInput_DropActiveItem;
    private readonly InputAction m_PlayerInput_Pause;
    private readonly InputAction m_PlayerInput_OK;
    private readonly InputAction m_PlayerInput_Jump;
    public struct PlayerInputActions
    {
        private @Controls m_Wrapper;
        public PlayerInputActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerInput_Movement;
        public InputAction @PointerPosition => m_Wrapper.m_PlayerInput_PointerPosition;
        public InputAction @AttackMainHand => m_Wrapper.m_PlayerInput_AttackMainHand;
        public InputAction @AttackOffHand => m_Wrapper.m_PlayerInput_AttackOffHand;
        public InputAction @SwitchWeapon => m_Wrapper.m_PlayerInput_SwitchWeapon;
        public InputAction @OverviewMapFullView => m_Wrapper.m_PlayerInput_OverviewMapFullView;
        public InputAction @NextLevel => m_Wrapper.m_PlayerInput_NextLevel;
        public InputAction @Interaction => m_Wrapper.m_PlayerInput_Interaction;
        public InputAction @SpecialMove1 => m_Wrapper.m_PlayerInput_SpecialMove1;
        public InputAction @SpecialMove2 => m_Wrapper.m_PlayerInput_SpecialMove2;
        public InputAction @SpecialMove3 => m_Wrapper.m_PlayerInput_SpecialMove3;
        public InputAction @BookView => m_Wrapper.m_PlayerInput_BookView;
        public InputAction @ActiveItem => m_Wrapper.m_PlayerInput_ActiveItem;
        public InputAction @DropActiveItem => m_Wrapper.m_PlayerInput_DropActiveItem;
        public InputAction @Pause => m_Wrapper.m_PlayerInput_Pause;
        public InputAction @OK => m_Wrapper.m_PlayerInput_OK;
        public InputAction @Jump => m_Wrapper.m_PlayerInput_Jump;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @PointerPosition.started += instance.OnPointerPosition;
            @PointerPosition.performed += instance.OnPointerPosition;
            @PointerPosition.canceled += instance.OnPointerPosition;
            @AttackMainHand.started += instance.OnAttackMainHand;
            @AttackMainHand.performed += instance.OnAttackMainHand;
            @AttackMainHand.canceled += instance.OnAttackMainHand;
            @AttackOffHand.started += instance.OnAttackOffHand;
            @AttackOffHand.performed += instance.OnAttackOffHand;
            @AttackOffHand.canceled += instance.OnAttackOffHand;
            @SwitchWeapon.started += instance.OnSwitchWeapon;
            @SwitchWeapon.performed += instance.OnSwitchWeapon;
            @SwitchWeapon.canceled += instance.OnSwitchWeapon;
            @OverviewMapFullView.started += instance.OnOverviewMapFullView;
            @OverviewMapFullView.performed += instance.OnOverviewMapFullView;
            @OverviewMapFullView.canceled += instance.OnOverviewMapFullView;
            @NextLevel.started += instance.OnNextLevel;
            @NextLevel.performed += instance.OnNextLevel;
            @NextLevel.canceled += instance.OnNextLevel;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @SpecialMove1.started += instance.OnSpecialMove1;
            @SpecialMove1.performed += instance.OnSpecialMove1;
            @SpecialMove1.canceled += instance.OnSpecialMove1;
            @SpecialMove2.started += instance.OnSpecialMove2;
            @SpecialMove2.performed += instance.OnSpecialMove2;
            @SpecialMove2.canceled += instance.OnSpecialMove2;
            @SpecialMove3.started += instance.OnSpecialMove3;
            @SpecialMove3.performed += instance.OnSpecialMove3;
            @SpecialMove3.canceled += instance.OnSpecialMove3;
            @BookView.started += instance.OnBookView;
            @BookView.performed += instance.OnBookView;
            @BookView.canceled += instance.OnBookView;
            @ActiveItem.started += instance.OnActiveItem;
            @ActiveItem.performed += instance.OnActiveItem;
            @ActiveItem.canceled += instance.OnActiveItem;
            @DropActiveItem.started += instance.OnDropActiveItem;
            @DropActiveItem.performed += instance.OnDropActiveItem;
            @DropActiveItem.canceled += instance.OnDropActiveItem;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @OK.started += instance.OnOK;
            @OK.performed += instance.OnOK;
            @OK.canceled += instance.OnOK;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
        }

        private void UnregisterCallbacks(IPlayerInputActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @PointerPosition.started -= instance.OnPointerPosition;
            @PointerPosition.performed -= instance.OnPointerPosition;
            @PointerPosition.canceled -= instance.OnPointerPosition;
            @AttackMainHand.started -= instance.OnAttackMainHand;
            @AttackMainHand.performed -= instance.OnAttackMainHand;
            @AttackMainHand.canceled -= instance.OnAttackMainHand;
            @AttackOffHand.started -= instance.OnAttackOffHand;
            @AttackOffHand.performed -= instance.OnAttackOffHand;
            @AttackOffHand.canceled -= instance.OnAttackOffHand;
            @SwitchWeapon.started -= instance.OnSwitchWeapon;
            @SwitchWeapon.performed -= instance.OnSwitchWeapon;
            @SwitchWeapon.canceled -= instance.OnSwitchWeapon;
            @OverviewMapFullView.started -= instance.OnOverviewMapFullView;
            @OverviewMapFullView.performed -= instance.OnOverviewMapFullView;
            @OverviewMapFullView.canceled -= instance.OnOverviewMapFullView;
            @NextLevel.started -= instance.OnNextLevel;
            @NextLevel.performed -= instance.OnNextLevel;
            @NextLevel.canceled -= instance.OnNextLevel;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @SpecialMove1.started -= instance.OnSpecialMove1;
            @SpecialMove1.performed -= instance.OnSpecialMove1;
            @SpecialMove1.canceled -= instance.OnSpecialMove1;
            @SpecialMove2.started -= instance.OnSpecialMove2;
            @SpecialMove2.performed -= instance.OnSpecialMove2;
            @SpecialMove2.canceled -= instance.OnSpecialMove2;
            @SpecialMove3.started -= instance.OnSpecialMove3;
            @SpecialMove3.performed -= instance.OnSpecialMove3;
            @SpecialMove3.canceled -= instance.OnSpecialMove3;
            @BookView.started -= instance.OnBookView;
            @BookView.performed -= instance.OnBookView;
            @BookView.canceled -= instance.OnBookView;
            @ActiveItem.started -= instance.OnActiveItem;
            @ActiveItem.performed -= instance.OnActiveItem;
            @ActiveItem.canceled -= instance.OnActiveItem;
            @DropActiveItem.started -= instance.OnDropActiveItem;
            @DropActiveItem.performed -= instance.OnDropActiveItem;
            @DropActiveItem.canceled -= instance.OnDropActiveItem;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @OK.started -= instance.OnOK;
            @OK.performed -= instance.OnOK;
            @OK.canceled -= instance.OnOK;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
        }

        public void RemoveCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);
    public interface IPlayerInputActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnPointerPosition(InputAction.CallbackContext context);
        void OnAttackMainHand(InputAction.CallbackContext context);
        void OnAttackOffHand(InputAction.CallbackContext context);
        void OnSwitchWeapon(InputAction.CallbackContext context);
        void OnOverviewMapFullView(InputAction.CallbackContext context);
        void OnNextLevel(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnSpecialMove1(InputAction.CallbackContext context);
        void OnSpecialMove2(InputAction.CallbackContext context);
        void OnSpecialMove3(InputAction.CallbackContext context);
        void OnBookView(InputAction.CallbackContext context);
        void OnActiveItem(InputAction.CallbackContext context);
        void OnDropActiveItem(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnOK(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
    }
}
